// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myHeroesAPI.Data;

#nullable disable

namespace myHeroesAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240119041926_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("myHeroesAPI.HeroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataNascimento");

                    b.Property<float>("Height")
                        .HasColumnType("real")
                        .HasColumnName("Altura");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Nome");

                    b.Property<string>("NameHero")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("NomeHeroi");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("Peso");

                    b.HasKey("Id");

                    b.ToTable("Hero");
                });

            modelBuilder.Entity("myHeroesAPI.SuperPowers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Descricao");

                    b.Property<int?>("HeroModelId")
                        .HasColumnType("int");

                    b.Property<string>("SuperPower")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Superpoder");

                    b.HasKey("Id");

                    b.HasIndex("HeroModelId");

                    b.ToTable("SuperPowers");
                });

            modelBuilder.Entity("myHeroesAPI.SuperPowers", b =>
                {
                    b.HasOne("myHeroesAPI.HeroModel", null)
                        .WithMany("Superpowers")
                        .HasForeignKey("HeroModelId");
                });

            modelBuilder.Entity("myHeroesAPI.HeroModel", b =>
                {
                    b.Navigation("Superpowers");
                });
#pragma warning restore 612, 618
        }
    }
}
